version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: '%(asctime)s | %(levelname)8s | %(name)20s | %(message)s'

handlers:
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: standard
    level: INFO
    filename: meltano.log  # Output file name
    maxBytes: 10485760  # 10 MB
    backupCount: 5

root:
  handlers: [file]
  level: INFO